//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace puntosVenta.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceOperacionesSoap")]
    public interface WebServiceOperacionesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        puntosVenta.ServiceReference1.HelloWorldResponse HelloWorld(puntosVenta.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<puntosVenta.ServiceReference1.HelloWorldResponse> HelloWorldAsync(puntosVenta.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precioVenta", ReplyAction="*")]
        double precioVenta(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precioVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<double> precioVentaAsync(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoMayoreo", ReplyAction="*")]
        double descuentoMayoreo(int stock, double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoMayoreo", ReplyAction="*")]
        System.Threading.Tasks.Task<double> descuentoMayoreoAsync(int stock, double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precioWiskey", ReplyAction="*")]
        double precioWiskey(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precioWiskey", ReplyAction="*")]
        System.Threading.Tasks.Task<double> precioWiskeyAsync(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precioTequila", ReplyAction="*")]
        double precioTequila(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precioTequila", ReplyAction="*")]
        System.Threading.Tasks.Task<double> precioTequilaAsync(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precioCerveza", ReplyAction="*")]
        double precioCerveza(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precioCerveza", ReplyAction="*")]
        System.Threading.Tasks.Task<double> precioCervezaAsync(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precioCoñaq", ReplyAction="*")]
        double precioCoñaq(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precioCoñaq", ReplyAction="*")]
        System.Threading.Tasks.Task<double> precioCoñaqAsync(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precioMedicamentos", ReplyAction="*")]
        double precioMedicamentos(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/precioMedicamentos", ReplyAction="*")]
        System.Threading.Tasks.Task<double> precioMedicamentosAsync(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IvaExento", ReplyAction="*")]
        int IvaExento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IvaExento", ReplyAction="*")]
        System.Threading.Tasks.Task<int> IvaExentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoPromocion5", ReplyAction="*")]
        double descuentoPromocion5(double precioVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoPromocion5", ReplyAction="*")]
        System.Threading.Tasks.Task<double> descuentoPromocion5Async(double precioVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoPromocion6", ReplyAction="*")]
        double descuentoPromocion6(double precioVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoPromocion6", ReplyAction="*")]
        System.Threading.Tasks.Task<double> descuentoPromocion6Async(double precioVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoPromocion7", ReplyAction="*")]
        double descuentoPromocion7(double precioVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoPromocion7", ReplyAction="*")]
        System.Threading.Tasks.Task<double> descuentoPromocion7Async(double precioVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoPromocion8", ReplyAction="*")]
        double descuentoPromocion8(double precioVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoPromocion8", ReplyAction="*")]
        System.Threading.Tasks.Task<double> descuentoPromocion8Async(double precioVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoPromocion9", ReplyAction="*")]
        double descuentoPromocion9(double precioVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoPromocion9", ReplyAction="*")]
        System.Threading.Tasks.Task<double> descuentoPromocion9Async(double precioVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoPromocion10", ReplyAction="*")]
        double descuentoPromocion10(double precioVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descuentoPromocion10", ReplyAction="*")]
        System.Threading.Tasks.Task<double> descuentoPromocion10Async(double precioVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/impuestoCoñaq", ReplyAction="*")]
        double impuestoCoñaq(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/impuestoCoñaq", ReplyAction="*")]
        System.Threading.Tasks.Task<double> impuestoCoñaqAsync(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/impuestoWiskey", ReplyAction="*")]
        double impuestoWiskey(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/impuestoWiskey", ReplyAction="*")]
        System.Threading.Tasks.Task<double> impuestoWiskeyAsync(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/impuestoTequila", ReplyAction="*")]
        double impuestoTequila(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/impuestoTequila", ReplyAction="*")]
        System.Threading.Tasks.Task<double> impuestoTequilaAsync(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/impuestoCerveza", ReplyAction="*")]
        double impuestoCerveza(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/impuestoCerveza", ReplyAction="*")]
        System.Threading.Tasks.Task<double> impuestoCervezaAsync(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/impuestoIVA", ReplyAction="*")]
        double impuestoIVA(double precioCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/impuestoIVA", ReplyAction="*")]
        System.Threading.Tasks.Task<double> impuestoIVAAsync(double precioCompra);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public puntosVenta.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(puntosVenta.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public puntosVenta.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(puntosVenta.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceOperacionesSoapChannel : puntosVenta.ServiceReference1.WebServiceOperacionesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceOperacionesSoapClient : System.ServiceModel.ClientBase<puntosVenta.ServiceReference1.WebServiceOperacionesSoap>, puntosVenta.ServiceReference1.WebServiceOperacionesSoap {
        
        public WebServiceOperacionesSoapClient() {
        }
        
        public WebServiceOperacionesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceOperacionesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceOperacionesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceOperacionesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        puntosVenta.ServiceReference1.HelloWorldResponse puntosVenta.ServiceReference1.WebServiceOperacionesSoap.HelloWorld(puntosVenta.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            puntosVenta.ServiceReference1.HelloWorldRequest inValue = new puntosVenta.ServiceReference1.HelloWorldRequest();
            inValue.Body = new puntosVenta.ServiceReference1.HelloWorldRequestBody();
            puntosVenta.ServiceReference1.HelloWorldResponse retVal = ((puntosVenta.ServiceReference1.WebServiceOperacionesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<puntosVenta.ServiceReference1.HelloWorldResponse> puntosVenta.ServiceReference1.WebServiceOperacionesSoap.HelloWorldAsync(puntosVenta.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<puntosVenta.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            puntosVenta.ServiceReference1.HelloWorldRequest inValue = new puntosVenta.ServiceReference1.HelloWorldRequest();
            inValue.Body = new puntosVenta.ServiceReference1.HelloWorldRequestBody();
            return ((puntosVenta.ServiceReference1.WebServiceOperacionesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public double precioVenta(double precioCompra) {
            return base.Channel.precioVenta(precioCompra);
        }
        
        public System.Threading.Tasks.Task<double> precioVentaAsync(double precioCompra) {
            return base.Channel.precioVentaAsync(precioCompra);
        }
        
        public double descuentoMayoreo(int stock, double precioCompra) {
            return base.Channel.descuentoMayoreo(stock, precioCompra);
        }
        
        public System.Threading.Tasks.Task<double> descuentoMayoreoAsync(int stock, double precioCompra) {
            return base.Channel.descuentoMayoreoAsync(stock, precioCompra);
        }
        
        public double precioWiskey(double precioCompra) {
            return base.Channel.precioWiskey(precioCompra);
        }
        
        public System.Threading.Tasks.Task<double> precioWiskeyAsync(double precioCompra) {
            return base.Channel.precioWiskeyAsync(precioCompra);
        }
        
        public double precioTequila(double precioCompra) {
            return base.Channel.precioTequila(precioCompra);
        }
        
        public System.Threading.Tasks.Task<double> precioTequilaAsync(double precioCompra) {
            return base.Channel.precioTequilaAsync(precioCompra);
        }
        
        public double precioCerveza(double precioCompra) {
            return base.Channel.precioCerveza(precioCompra);
        }
        
        public System.Threading.Tasks.Task<double> precioCervezaAsync(double precioCompra) {
            return base.Channel.precioCervezaAsync(precioCompra);
        }
        
        public double precioCoñaq(double precioCompra) {
            return base.Channel.precioCoñaq(precioCompra);
        }
        
        public System.Threading.Tasks.Task<double> precioCoñaqAsync(double precioCompra) {
            return base.Channel.precioCoñaqAsync(precioCompra);
        }
        
        public double precioMedicamentos(double precioCompra) {
            return base.Channel.precioMedicamentos(precioCompra);
        }
        
        public System.Threading.Tasks.Task<double> precioMedicamentosAsync(double precioCompra) {
            return base.Channel.precioMedicamentosAsync(precioCompra);
        }
        
        public int IvaExento() {
            return base.Channel.IvaExento();
        }
        
        public System.Threading.Tasks.Task<int> IvaExentoAsync() {
            return base.Channel.IvaExentoAsync();
        }
        
        public double descuentoPromocion5(double precioVenta) {
            return base.Channel.descuentoPromocion5(precioVenta);
        }
        
        public System.Threading.Tasks.Task<double> descuentoPromocion5Async(double precioVenta) {
            return base.Channel.descuentoPromocion5Async(precioVenta);
        }
        
        public double descuentoPromocion6(double precioVenta) {
            return base.Channel.descuentoPromocion6(precioVenta);
        }
        
        public System.Threading.Tasks.Task<double> descuentoPromocion6Async(double precioVenta) {
            return base.Channel.descuentoPromocion6Async(precioVenta);
        }
        
        public double descuentoPromocion7(double precioVenta) {
            return base.Channel.descuentoPromocion7(precioVenta);
        }
        
        public System.Threading.Tasks.Task<double> descuentoPromocion7Async(double precioVenta) {
            return base.Channel.descuentoPromocion7Async(precioVenta);
        }
        
        public double descuentoPromocion8(double precioVenta) {
            return base.Channel.descuentoPromocion8(precioVenta);
        }
        
        public System.Threading.Tasks.Task<double> descuentoPromocion8Async(double precioVenta) {
            return base.Channel.descuentoPromocion8Async(precioVenta);
        }
        
        public double descuentoPromocion9(double precioVenta) {
            return base.Channel.descuentoPromocion9(precioVenta);
        }
        
        public System.Threading.Tasks.Task<double> descuentoPromocion9Async(double precioVenta) {
            return base.Channel.descuentoPromocion9Async(precioVenta);
        }
        
        public double descuentoPromocion10(double precioVenta) {
            return base.Channel.descuentoPromocion10(precioVenta);
        }
        
        public System.Threading.Tasks.Task<double> descuentoPromocion10Async(double precioVenta) {
            return base.Channel.descuentoPromocion10Async(precioVenta);
        }
        
        public double impuestoCoñaq(double precioCompra) {
            return base.Channel.impuestoCoñaq(precioCompra);
        }
        
        public System.Threading.Tasks.Task<double> impuestoCoñaqAsync(double precioCompra) {
            return base.Channel.impuestoCoñaqAsync(precioCompra);
        }
        
        public double impuestoWiskey(double precioCompra) {
            return base.Channel.impuestoWiskey(precioCompra);
        }
        
        public System.Threading.Tasks.Task<double> impuestoWiskeyAsync(double precioCompra) {
            return base.Channel.impuestoWiskeyAsync(precioCompra);
        }
        
        public double impuestoTequila(double precioCompra) {
            return base.Channel.impuestoTequila(precioCompra);
        }
        
        public System.Threading.Tasks.Task<double> impuestoTequilaAsync(double precioCompra) {
            return base.Channel.impuestoTequilaAsync(precioCompra);
        }
        
        public double impuestoCerveza(double precioCompra) {
            return base.Channel.impuestoCerveza(precioCompra);
        }
        
        public System.Threading.Tasks.Task<double> impuestoCervezaAsync(double precioCompra) {
            return base.Channel.impuestoCervezaAsync(precioCompra);
        }
        
        public double impuestoIVA(double precioCompra) {
            return base.Channel.impuestoIVA(precioCompra);
        }
        
        public System.Threading.Tasks.Task<double> impuestoIVAAsync(double precioCompra) {
            return base.Channel.impuestoIVAAsync(precioCompra);
        }
    }
}
