//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uttt.Rest.SqlApi.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class basetestmodelEntities2 : DbContext
    {
        public basetestmodelEntities2()
            : base("name=basetestmodelEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Telefonos> Telefonos { get; set; }
    }
}
